layer: add missing header after 540323ac37fc
layer/VkLayer_FROG_gamescope_wsi.cpp:53:5: error: use of undeclared identifier 'pread'
    pread(fd, &overrideValue, sizeof(overrideValue), 0);
    ^